# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=2000)),
                ('organism', models.CharField(max_length=200)),
                ('experiment_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.CharField(max_length=50)),
                ('experiment_type', models.CharField(max_length=200)),
                ('experiment_description', models.TextField()),
                ('experiment_link', models.CharField(max_length=200)),
            ],
        ),
    ]
