# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_id',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
